### ISSUE TITLE
Changing Evaluation

### ISSUE THREAD

**Issue by philip-ulrich** [jeremyprice/class_scratchpad#18]
I think we need to re look at commit 8ef379dc0a2f66ca048499d753a49d62ffd2ffed and consider modify it's contents.

**Comment by philip-ulrich** [comment]
I believe that we have fixed the issue. Any other thoughts?

**Comment by jeremyprice** [comment]
I agree that the contents of that commit are WAY too specific.

**Comment by jeremyprice** [comment]
What effect will this have on 86448530f3cc564ac4239384904d8dcaef625385 ?

**Comment by philip-ulrich** [comment]
Should have no effect as d8bdbfd and 8644853 have no common dependancies and are not dependant on each other in any way.

**Comment by philip-ulrich** [comment]
0a0eeff definitely will cause issues with this. I think we need to close out PR #20

**Comment by asrielagronin** [comment]
What about PR 21

**Comment by jeremyprice** [comment]
Looks like this issue is good-to-go.  Closing it.
